_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 49
                - 55
            "2":
                - 1
                - 49
                - 55
            "3":
                - 3
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.8
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
environment:
    value:
        action_space_accel_disc: 7
        action_space_steer_disc: 13
        closest_k_parnters_in_history: all
        collision_behavior: ignore
        collision_weight: -0.75
        collision_weight_lb: -1
        collision_weight_ub: -0.9
        condition_mode: random
        dataset_size: 2
        dist_to_goal_threshold: 2
        dynamics_model: classic
        ego_state: true
        goal_achieved_weight: 1
        goal_achieved_weight_lb: 1.9
        goal_achieved_weight_ub: 2
        k_trials: 0
        k_unique_scenes: 2
        lidar_obs: false
        log_history_step: 10
        max_controlled_agents: 64
        max_seq_len: 0
        name: gpudriveConditioned
        norm_obs: true
        num_steps: 91
        num_worlds: 2
        obs_radius: 50
        off_road_weight: -0.75
        off_road_weight_lb: -1
        off_road_weight_ub: -0.9
        partner_obs: true
        polyline_reduction_threshold: 0.1
        remove_non_vehicles: true
        reward_type: reward_conditioned
        road_map_obs: true
        sampling_seed: 42
        use_vbd: false
        vbd_in_obs: false
exp_id:
    value: PPO_Conditioned__S_2__Cond_random__06_02_00_53_16_113
network_arch:
    value:
        class_name: LateFusion
        dropout: 0.01
        hidden_dim: 128
        input_dim: 64
        num_parameters: 51420
network_class:
    value: NeuralNet
train:
    value:
        anneal_lr: false
        batch_size: 512
        bptt_horizon: 1
        checkpoint_interval: 400
        checkpoint_path: ./runs
        clip_coef: 0.2
        clip_vloss: false
        compile: false
        compile_mode: reduce-overhead
        cpu_offload: false
        device: cuda
        ent_coef: 0.0001
        env: gpudriveConditioned
        exp_id: PPO_Conditioned__S_2__Cond_random__06_02_00_53_16_113
        gae_lambda: 0.95
        gamma: 0.99
        learning_rate: "3e-4"
        log_window: 1000
        max_grad_norm: 0.5
        minibatch_size: 16
        network:
            class_name: LateFusion
            dropout: 0.01
            hidden_dim: 128
            input_dim: 64
            num_parameters: 51420
        norm_adv: true
        render: false
        render_3d: true
        render_format: mp4
        render_fps: 15
        render_interval: 1
        render_k_scenarios: 10
        resample_dataset_size: 10000
        resample_interval: 2000000
        resample_scenes: false
        sample_with_replacement: true
        seed: 42
        shuffle_dataset: false
        target_kl: null
        torch_deterministic: false
        total_timesteps: 1000000000
        update_epochs: 4
        vf_clip_coef: 0.2
        vf_coef: 0.3
        zoom_radius: 50
vec:
    value:
        backend: native
        env_batch_size: 1
        num_workers: 1
        zero_copy: false
