data_dir: "data/processed/examples"

num_worlds: 50

selection_discipline: "K_UNIQUE_N"  # K_UNIQUE_N / PAD_N
k_unique_scenes: 3
device: "cuda"  # or "cpu"

reward_type: "weighted_combination"
collision_weight: 0.0
goal_achieved_weight: 1.0
off_road_weight: 0.0

resample_scenarios: false
resample_criterion: "global_step"  # Options: "global_step"
resample_freq: 1_000_000  # Resample every k steps (recommended to be a multiple of num_worlds * n_steps)
resample_mode: "random"  # Options: "random"

render: true
render_mode: "rgb_array"
render_freq: 500  # Render every k rollouts
render_n_worlds: 3  # Number of worlds to render

track_time_to_solve: false

sync_tensorboard: true
logging_collection_window: 100  # How many trajectories we average logs over
log_freq: 100
project_name: "gpudrive"
group_name: " "
entity: " "
tags: 
  - "IPPO"
  - "LATE_FUSION"
  - "PERM_EQ"
wandb_mode: "online"  # Options: online, offline, disabled

episode_len: 91  # Length of an episode in the simulator

save_policy: true
save_policy_freq: 200

seed: 42
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: null
vf_coef: 0.5
n_steps: 91  # Number of steps per rollout
num_minibatches: 5  # Used to determine the minibatch size
verbose: 0
total_timesteps: 30_000_00000
ent_coef: 0.0001
lr: 0.0003
n_epochs: 5

mlp_class: "late_fusion"
policy: "late_fusion_policy"
ego_state_layers: 
  - 64
  - 32
road_object_layers: 
  - 64
  - 64
road_graph_layers: 
  - 64
  - 64
shared_layers: 
  - 64
  - 64
act_func: "tanh"
dropout: 0.0
last_layer_dim_pi: 64
last_layer_dim_vf: 64
